services:
  api:
    container_name: api
    image: api-image:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5132:5132
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
